Support for scan codes
rukai/winit_input_helper pull request #35
Opened 2023-06-14 16:55 UTC by Zstorm999

This PR implements issue #33. 

I added 4 new functions : 
- `key_pressed_scancode`
- `key_pressed_os_scancode`
- `key_released_scancode`
- `key_held_scancode`

And modified the example accordingly.

The code is very similar to what was already done with VirtualKeyCodes, except for the held part. Some scan codes (at least on my keyboard) are higher than 255, so using an array was not practical. Instead I used a Vec, checking if it already contains the specified key when needed.

2023-06-17 03:58 UTC, rukai commented
Hi, thanks for the PR!
I agree with your point that not supporting scancodes is poor support for international keyboards.
It will take me a while to evaluate your approach, in the meantime you can run `cargo fmt` to address the CI failure. Sorry about github refusing to run CI until I manually approve it.

2023-06-17 04:22 UTC, rukai requested changes
I'm generally happy with this approach.
I considered combining `scancode_actions` and `key_actions` to avoid allocating the extra vec, but its not clear that would improve anything.
Just address the feedback + `cargo fmt` and we should be right to merge.

2023-06-17 04:22 UTC, rukai commented on src/current_input.rs
> +                        // no handling for the back key as a scancode
I think this is self-obvious and doesnt need a comment

2023-06-17 04:22 UTC, rukai commented on src/winit_input_helper.rs
> +    /// This is suitable for game controls that do not depend on the user  keyboard layout.
extra space here `user  keyboard`

2023-06-17 14:19 UTC, Zstorm999 commented
Applied your feedback and ran `cargo fmt`, should be good now

2023-06-18 21:58 UTC, rukai approved these changes
Thanks!

2023-06-18 21:58 UTC, merged